apiVersion: policy.mcm.ibm.com/v1alpha1
kind: Policy
metadata:
  name: policy-iampolicy
  namespace: kube-system
  annotations:
    policy.mcm.ibm.com/standards: NIST-CSF
    policy.mcm.ibm.com/categories: PR.AC Identity Management Authentication and Access Control
    policy.mcm.ibm.com/controls: PR.AC-4 Access Control
spec:
  complianceType: musthave
  remediationAction: inform
  disabled: false
  namespaces:
    exclude: ["kube-*"]
    include: ["default"]
  policy-templates:
    - objectDefinition:
        apiVersion: iam.policies.ibm.com/v1alpha1
        kind: IamPolicy # limit clusteradminrole and report violation in IAM RBAC
        metadata:
          name: policy-iampolicy-example
        spec:
          severity: medium
          namespaceSelector:
            include: ["default","kube-*"]
            exclude: ["kube-system"]
          remediationAction: inform
          maxClusterRoleBindingUsers: 10
          maxRoleBindingViolationsPerNamespace: 2
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: binding-policy-iampolicy
  namespace: kube-system
placementRef:
  name: placement-policy-iampolicy
  kind: PlacementPolicy
  apiGroup: mcm.ibm.com
subjects:
- name: policy-iampolicy
  kind: Policy
  apiGroup: policy.mcm.ibm.com
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: placement-policy-iampolicy
  namespace: kube-system
spec:
  clusterLabels:
    matchExpressions:
      - {key: cloud, operator: In, values: ["MyDataCenter1", "MyDataCenter2"]}
