apiVersion: policy.mcm.ibm.com/v1alpha1
kind: Policy
metadata:
  name: policy-mutationpolicy
  namespace: kube-system
  annotations:
    policy.mcm.ibm.com/standards: NIST-CSF
    policy.mcm.ibm.com/categories: DE.CM Security Continuous Monitoring
    policy.mcm.ibm.com/controls: DE.CM-7 Monitoring for unauthorized activity
spec:
  complianceType: musthave
  remediationAction: inform
  disabled: false
  namespaces:
    exclude: ["kube-*"]
    include: ["default"]
  policy-templates:
    - objectDefinition:
        apiVersion: policies.ibm.com/v1alpha1
        kind: MutationPolicy # no mutation allowed
        metadata:
          name: policy-mutationpolicy-example
        spec:
          namespaceSelector:
            include: ["default","kube-*"]
            exclude: ["kube-system"]
          remediationAction: inform # enforce or inform
          severity: medium
          conditions:
            ownership: ["ReplicaSet", "Deployment", "DeamonSet", "ReplicationController", "none"]
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: binding-policy-mutationpolicy
  namespace: kube-system
placementRef:
  name: placement-policy-mutationpolicy
  kind: PlacementPolicy
  apiGroup: mcm.ibm.com
subjects:
- name: policy-mutationpolicy
  kind: Policy
  apiGroup: policy.mcm.ibm.com
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: placement-policy-mutationpolicy
  namespace: kube-system
spec:
  clusterLabels:
    matchExpressions:
      - {key: cloud, operator: In, values: ["MyDataCenter1", "MyDataCenter2"]}
